library(pglm)
library(haven)
library(dplyr)
options(scipen = 10)

# set path
ROOT <- getwd() # set it to your repository root path
SRC <- paste0(ROOT, "/src/")
BLD <- paste0(ROOT, "/bld/")

# read data generated by python
merge_data <- read_dta(paste0(BLD,"data/liss/logit_merge_data.dta"))

# set individual and time column name for panel data
panal_data <- pdata.frame(merge_data, index = c('personal_id','month'))

# x is all columns in panal_data except y, individual, time and const
x_var <- colnames(panal_data)[! colnames(panal_data) %in% c('infected','personal_id','month','_const')]
formula <- paste0("infected ~ ", paste(x_var, collapse='+'))

# run regression
fit <- pglm(formula, data=panal_data, model="random",family = binomial('logit'))
summary(fit)